### ISSUE TITLE
[!!] Inconsistency with capital letters after bullets

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-components#7]
Introduction section - uses lower case to start each bullet except for one time.
Interdependencies Between Components section - uses capital letters to start each bullet

I believe that the Introduction section should start with capital letters for each of the 7 bullets.

**Comment by shawna-slh** [comment]
Good catch. (although I would have marked it [ED] :-) 

According to our [style guide](https://www.w3.org/WAI/EO/wiki/Style#Lists), they could be lower or upper. Slight leaning toward lowercase since they could all be in one (looong) sentence.

I prefer the style of lowercase for these. I updated all.

I also updated Web-> web and Web sites -> websites -- per the Style Guide.
